services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: pass1234
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
#    restart: always

  redis:
    image: redis:7
    ports:
      - "6379:6379"
#    restart: always